create table pessoa (id serial primary key, nome varchar(50));
insert into pessoa (nome) values ('Mauro');
insert into pessoa (nome) values ('Victor');
create table aluno (id serial primary key, nome varchar(50), curso varchar(50));
create table carro(id serial primary key, marca varchar(50), linha varchar(50), modelo varchar(50), ano_modelo varchar(50));
create table filial(id serial primary key, logradouro varchar(50), endereco varchar(50), numero int, bairro varchar(50));
create table conta(id serial primary key, email varchar(50), senha varchar(50));
create table cliente (id serial primary key, nome varchar(50));
create table documento (id serial primary key, seq varchar(3), titulo varchar(50));
create table cena (id serial primary key, seq varchar(3), titulo varchar(50));
create table atleta (id serial primary key, nome varchar(50), modalidade varchar(50));
insert into atleta (nome, modalidade) values ('Marta', 'Futebol');
insert into atleta (nome, modalidade) values ('Michael Jordan', 'Basquete');
insert into atleta (nome, modalidade) values ('Daniel Negreanu', 'Poker');
create table musica (autor varchar(50), nome varchar(50), ano int);
create table jogo (id serial primary key, nome varchar(50));
insert into jogo (nome) values ('Uncharted');
insert into jogo (nome) values ('Resident Evil 4');
create table tarefa(id serial primary key, descricao varchar(50));
create table etapa(id serial primary key, descricao varchar(50));
insert into etapa (descricao) values ('Etapa 1');
create table item(id serial primary key, descricao varchar(50));
create table issue(id serial primary key, descricao varchar(50));
create table association(id serial primary key, issue_father int, issue_child int);
create table ticket(id serial primary key, descricao varchar(50));