create table "Pessoa" (id serial primary key, nome varchar(50));
insert into "Pessoa" (nome) values ('Mauro');
insert into "Pessoa" (nome) values ('Victor');
create table "Aluno" (id serial primary key, nome varchar(50), curso varchar(50));
create table "Carro" (id serial primary key, marca varchar(50), linha varchar(50), modelo varchar(50), ano_modelo varchar(50));
create table "Filial" (id serial primary key, logradouro varchar(50), endereco varchar(50), numero int, bairro varchar(50));
create table "Conta"(id serial primary key, email varchar(50), senha varchar(50));
create table "Cliente" (id serial primary key, nome varchar(50));
create table "Documento" (id serial primary key, seq varchar(3), titulo varchar(50));
create table "Cena" (id serial primary key, seq varchar(3), titulo varchar(50));
create table "Atleta" (id serial primary key, nome varchar(50), modalidade varchar(50));
insert into "Atleta" (nome, modalidade) values ('Marta', 'Futebol');
insert into "Atleta" (nome, modalidade) values ('Michael Jordan', 'Basquete');
insert into "Atleta" (nome, modalidade) values ('Daniel Negreanu', 'Poker');
create table "Musica" (autor varchar(50), nome varchar(50), ano int);
create table "Jogo" (id serial primary key, nome varchar(50));
insert into "Jogo" (nome) values ('Uncharted');
insert into "Jogo" (nome) values ('Resident Evil 4');
create table "Tarefa" (id serial primary key, descricao varchar(50));
create table "Etapa"(id serial primary key, descricao varchar(50));
insert into "Etapa" (descricao) values ('Etapa 1');
create table "Item" (id serial primary key, descricao varchar(50));
create table "Issue"(id serial primary key, descricao varchar(50));
create table "Association"(id serial primary key, issue_father int, issue_child int);
create table "Ticket"(id serial primary key, descricao varchar(50));
create table "Leitor"(id serial primary key, nome varchar(50));
insert into "Leitor" (nome) values ('Pedro');
insert into "Leitor" (nome) values ('Hebert');
insert into "Leitor" (nome) values ('Guilherme');
create table "Livro"(id serial primary key, seq varchar(3), titulo varchar(50));
insert into "Livro" (seq, titulo) values ('001', 'Título A');
insert into "Livro" (seq, titulo) values ('001', 'Título B');
insert into "Livro" (seq, titulo) values ('002', 'Título C');
create table "Roteiro" (id serial primary key, seq varchar(3), titulo varchar(50));
insert into "Roteiro" (seq, titulo) values ('001', 'Título A');
insert into "Roteiro" (seq, titulo) values ('001', 'Título B');
insert into "Roteiro" (seq, titulo) values ('002', 'Título C');